- hosts: all  
  tasks:
  - name: install packages
    yum:
      name: 
        - httpd
        - git
        - wget
      state: latest

  - name: Start service httpd, if not started
    service:
     name: httpd
     state: started
     enabled: yes

  - name: Stop service httpd,
    service:
     name: httpd
     state: stopped

  - name: Remove git
    yum:
      name: git
      state: absent

  # - name: install git
  #   yum:
  #     name: git
  #     state: absent
