- hosts: all
  become: yes
  tasks: 
  - hostname: 
      name: "{{ inventory_hostname }}"

  - debug: msg="{{ ansible_distribution }}"
  - name: Install Apache
    include_tasks: "{{ ansible_distribution }}.yml"

# - hosts: master
#   tasks: 
#   - hostname: 
#       name: centos7

# - hosts: worker1
#   tasks: 
#   - hostname: 
#       name: ubuntu22

# - hosts: worker2
#   become: yes
#   tasks: 
#   - hostname: 
#       name: amazon2

# - hosts: worker3
#   become: yes
#   tasks: 
#   - hostname: 
#       name: amazon3